PREFIX files: <http://lynx.lblod.info/files/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/> 
PREFIX sioc: <http://rdfs.org/sioc/ns#>	

INSERT DATA { 
    GRAPH <http://mu.semte.ch/application> {
        $fileId sioc:content $extractedText . 
    } 
}